const {
  S3_BUCKET_URL,
  S3_BUCKET_PATH,
  S3_BUCKET_NAME,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY
} = process.env;

export {
  S3_BUCKET_URL,
  S3_BUCKET_PATH,
  S3_BUCKET_NAME,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY
};
